{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_debug-1.0.aar",
          "url": "share_plus_debug-1.0.aar",
          "size": 23085,
          "sha512": "45ecb4a536301531bead8436456779e710d91e66190e112639c2b8e95c42a10a84a0475c9bf5cc499f88bfe6a83225c4b25ac2fd0bdf3ba21c8680b3ce0ca1bc",
          "sha256": "08a4c9d6ef05e4fee3bab05324e606407429b43622087e84bfb1eb8624d46afa",
          "sha1": "0e8e0c0e014350c49c4d67fbee75ae46d4c12538",
          "md5": "573ac1bb5cf3debc1d3921e0c65b8484"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_debug-1.0.aar",
          "url": "share_plus_debug-1.0.aar",
          "size": 23085,
          "sha512": "45ecb4a536301531bead8436456779e710d91e66190e112639c2b8e95c42a10a84a0475c9bf5cc499f88bfe6a83225c4b25ac2fd0bdf3ba21c8680b3ce0ca1bc",
          "sha256": "08a4c9d6ef05e4fee3bab05324e606407429b43622087e84bfb1eb8624d46afa",
          "sha1": "0e8e0c0e014350c49c4d67fbee75ae46d4c12538",
          "md5": "573ac1bb5cf3debc1d3921e0c65b8484"
        }
      ]
    }
  ]
}
