{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_debug-1.0.aar",
          "url": "webview_flutter_android_debug-1.0.aar",
          "size": 155105,
          "sha512": "8b3ce3531ecbf054950531ed66d297a9f67ed45ed9fd340e92113058a43f0ed47e899c60832989061296445c3b897dda678acd28608a2b67b53b7a8f847095c2",
          "sha256": "9fbe4af7ee7d7242e6bd0fec14af14e4c22d86f444221acb022444e6ee5a003f",
          "sha1": "6b198b83f244de9f2e281d9ec2e1d60c55ecbe5e",
          "md5": "bc3873f9abc1dc8532a7eff129624392"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_debug-1.0.aar",
          "url": "webview_flutter_android_debug-1.0.aar",
          "size": 155105,
          "sha512": "8b3ce3531ecbf054950531ed66d297a9f67ed45ed9fd340e92113058a43f0ed47e899c60832989061296445c3b897dda678acd28608a2b67b53b7a8f847095c2",
          "sha256": "9fbe4af7ee7d7242e6bd0fec14af14e4c22d86f444221acb022444e6ee5a003f",
          "sha1": "6b198b83f244de9f2e281d9ec2e1d60c55ecbe5e",
          "md5": "bc3873f9abc1dc8532a7eff129624392"
        }
      ]
    }
  ]
}
