{
  "formatVersion": "1.1",
  "component": {
    "group": "com.syncfusion.flutter.pdfviewer",
    "module": "syncfusion_flutter_pdfviewer_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer_release-1.0.aar",
          "url": "syncfusion_flutter_pdfviewer_release-1.0.aar",
          "size": 10194,
          "sha512": "d3b644c445077ae185940294a74f08b671ad37522201e05537f4f563a3ede8212a51460dad435f0aee484fd3936a998454f7cc8cbe58dfcea7c24f49de2bbdde",
          "sha256": "77a72ac88b73163c5b394a46968bd601a5a33bb259bff66d80d49ae9d58ac53a",
          "sha1": "1c8a453632806641ed348966be92282fad506a8a",
          "md5": "a4a688d35f08aedd8cc4a8a28b2d7e1b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer_release-1.0.aar",
          "url": "syncfusion_flutter_pdfviewer_release-1.0.aar",
          "size": 10194,
          "sha512": "d3b644c445077ae185940294a74f08b671ad37522201e05537f4f563a3ede8212a51460dad435f0aee484fd3936a998454f7cc8cbe58dfcea7c24f49de2bbdde",
          "sha256": "77a72ac88b73163c5b394a46968bd601a5a33bb259bff66d80d49ae9d58ac53a",
          "sha1": "1c8a453632806641ed348966be92282fad506a8a",
          "md5": "a4a688d35f08aedd8cc4a8a28b2d7e1b"
        }
      ]
    }
  ]
}
