{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_debug-1.0.aar",
          "url": "flutter_secure_storage_debug-1.0.aar",
          "size": 27887,
          "sha512": "f14f93cdedf8410f71f936a42077afc2a8d5fb4f27e90cfbc3bae8cf16d3fe9246bb0ea0c69d343265ba8a38081e7006b1f6f56c3a4a9547eb543ebd67420f0e",
          "sha256": "fde8585cc48ff72deb63e6a612d94e084a0ce7bdda448cb5fa1b7a99d0d2af4b",
          "sha1": "d9f728c1afeae01bcdca16f2bc38c03db9973ad8",
          "md5": "6d931a8bd59fc5802fd778e539c1a54f"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_debug-1.0.aar",
          "url": "flutter_secure_storage_debug-1.0.aar",
          "size": 27887,
          "sha512": "f14f93cdedf8410f71f936a42077afc2a8d5fb4f27e90cfbc3bae8cf16d3fe9246bb0ea0c69d343265ba8a38081e7006b1f6f56c3a4a9547eb543ebd67420f0e",
          "sha256": "fde8585cc48ff72deb63e6a612d94e084a0ce7bdda448cb5fa1b7a99d0d2af4b",
          "sha1": "d9f728c1afeae01bcdca16f2bc38c03db9973ad8",
          "md5": "6d931a8bd59fc5802fd778e539c1a54f"
        }
      ]
    }
  ]
}
