{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.packageinfo",
    "module": "package_info_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-1.0.aar",
          "url": "package_info_plus_release-1.0.aar",
          "size": 7926,
          "sha512": "33c9d25eaa9815d03753ba4c972e0d60f9a67c502b0e759c3b7d593d48988edadc9adef782d117a822f6c9bb8ccdadd8490ac71d2c33421ee4a2288d7bac9c7c",
          "sha256": "ecb6a2a462c6e4e63104b749ac4e8fd336ea859b7758f1d953a091fd1581a792",
          "sha1": "a651344bad97aaaeb24307be3c6fa36fd62d773a",
          "md5": "33921e3e5cfa2223025b6efb0d711ac6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-1.0.aar",
          "url": "package_info_plus_release-1.0.aar",
          "size": 7926,
          "sha512": "33c9d25eaa9815d03753ba4c972e0d60f9a67c502b0e759c3b7d593d48988edadc9adef782d117a822f6c9bb8ccdadd8490ac71d2c33421ee4a2288d7bac9c7c",
          "sha256": "ecb6a2a462c6e4e63104b749ac4e8fd336ea859b7758f1d953a091fd1581a792",
          "sha1": "a651344bad97aaaeb24307be3c6fa36fd62d773a",
          "md5": "33921e3e5cfa2223025b6efb0d711ac6"
        }
      ]
    }
  ]
}
