{
  "formatVersion": "1.1",
  "component": {
    "group": "com.syncfusion.flutter.pdfviewer",
    "module": "syncfusion_flutter_pdfviewer_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer_debug-1.0.aar",
          "url": "syncfusion_flutter_pdfviewer_debug-1.0.aar",
          "size": 10591,
          "sha512": "5202a81183e304e3bb7c4596b81c6efc7a9a6a1ce34416e8a89151c51a780107ecd4cb467a39931430def2753e27c696fc784ee564fc2f4171f05019acb6409c",
          "sha256": "b14139efa9ef91f497f8a1ce5d9327c56445e141bcd399c394173efdaec941fd",
          "sha1": "8eb36283047312b57b5c969b6e6dc15e3b4284ee",
          "md5": "73f9b26a59ee2bbc156717932a5c2ee6"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer_debug-1.0.aar",
          "url": "syncfusion_flutter_pdfviewer_debug-1.0.aar",
          "size": 10591,
          "sha512": "5202a81183e304e3bb7c4596b81c6efc7a9a6a1ce34416e8a89151c51a780107ecd4cb467a39931430def2753e27c696fc784ee564fc2f4171f05019acb6409c",
          "sha256": "b14139efa9ef91f497f8a1ce5d9327c56445e141bcd399c394173efdaec941fd",
          "sha1": "8eb36283047312b57b5c969b6e6dc15e3b4284ee",
          "md5": "73f9b26a59ee2bbc156717932a5c2ee6"
        }
      ]
    }
  ]
}
