{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_debug-1.0.aar",
          "url": "permission_handler_android_debug-1.0.aar",
          "size": 30184,
          "sha512": "d81d59f5637dd30cebb617223e9664a60b2c7072dde26aeb4ee144856918768bf9546e714e6b4362645cd153051b0a4ce04a5a8a95a7eb295a9e23bbecedd41a",
          "sha256": "a334c96bf1ad187099c956b50dc9eb56c7011e47b7726fc362d296e33b6db516",
          "sha1": "723935520e9178a445611e17ea005bf9c91344c1",
          "md5": "4e6e5c849cfa0b19e263665bfc6a082d"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_debug-1.0.aar",
          "url": "permission_handler_android_debug-1.0.aar",
          "size": 30184,
          "sha512": "d81d59f5637dd30cebb617223e9664a60b2c7072dde26aeb4ee144856918768bf9546e714e6b4362645cd153051b0a4ce04a5a8a95a7eb295a9e23bbecedd41a",
          "sha256": "a334c96bf1ad187099c956b50dc9eb56c7011e47b7726fc362d296e33b6db516",
          "sha1": "723935520e9178a445611e17ea005bf9c91344c1",
          "md5": "4e6e5c849cfa0b19e263665bfc6a082d"
        }
      ]
    }
  ]
}
