{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vnpt.smartca.module.vnpt_smartca_module",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.syncfusion.flutter.pdfviewer",
          "module": "syncfusion_flutter_pdfviewer_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.deviceinfo",
          "module": "device_info_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jrai.flutter_keyboard_visibility",
          "module": "flutter_keyboard_visibility_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_file_safe_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "appmire.be.flutterjailbreakdetection",
          "module": "flutter_jailbreak_detection_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 24708781,
          "sha512": "2adfc1c52d97737be4f82f008eedbdd2ce1d6b395236f4e92d4c970ef35eee2a174210952c9dc84a1220a152947bd7b844d7de60e3317ab9848b91299da2cebc",
          "sha256": "9579bdc7a1b22bff52e33162229ba0348b9969d920fc7e23ae7258986d3f4b36",
          "sha1": "a5f27e8849fb83896da66414c709cc895c3dea0f",
          "md5": "c8015f8a6085cde6f8f15c1a9a3ea303"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.syncfusion.flutter.pdfviewer",
          "module": "syncfusion_flutter_pdfviewer_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.deviceinfo",
          "module": "device_info_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jrai.flutter_keyboard_visibility",
          "module": "flutter_keyboard_visibility_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_file_safe_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "appmire.be.flutterjailbreakdetection",
          "module": "flutter_jailbreak_detection_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 24708781,
          "sha512": "2adfc1c52d97737be4f82f008eedbdd2ce1d6b395236f4e92d4c970ef35eee2a174210952c9dc84a1220a152947bd7b844d7de60e3317ab9848b91299da2cebc",
          "sha256": "9579bdc7a1b22bff52e33162229ba0348b9969d920fc7e23ae7258986d3f4b36",
          "sha1": "a5f27e8849fb83896da66414c709cc895c3dea0f",
          "md5": "c8015f8a6085cde6f8f15c1a9a3ea303"
        }
      ]
    }
  ]
}
