{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.0.aar",
          "url": "url_launcher_android_release-1.0.aar",
          "size": 23297,
          "sha512": "11761aac541b5834916ad55570e3be2ce420ca8dddd14a6e8b8ff2448906c3901e54f36a56e6f6946be2b490ceee64d58aaef1a01d18c4d42d0ce2254a0d9f35",
          "sha256": "fe563701285261152ccb8705841b660e2a6c810ad5bf8a0b0b85ed7d47ea64c0",
          "sha1": "51205873717c29cd6e44f941a51cce6e9d701679",
          "md5": "b6632984f6553667ad06f92b6608e241"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.0.aar",
          "url": "url_launcher_android_release-1.0.aar",
          "size": 23297,
          "sha512": "11761aac541b5834916ad55570e3be2ce420ca8dddd14a6e8b8ff2448906c3901e54f36a56e6f6946be2b490ceee64d58aaef1a01d18c4d42d0ce2254a0d9f35",
          "sha256": "fe563701285261152ccb8705841b660e2a6c810ad5bf8a0b0b85ed7d47ea64c0",
          "sha1": "51205873717c29cd6e44f941a51cce6e9d701679",
          "md5": "b6632984f6553667ad06f92b6608e241"
        }
      ]
    }
  ]
}
