{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.deviceinfo",
    "module": "device_info_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_release-1.0.aar",
          "url": "device_info_release-1.0.aar",
          "size": 7939,
          "sha512": "84801cf178e1cbdff4c8d043cab3bf1c4e111c1ee390ca7127722ad7145ba881851b32614f62778095c0dec04fcab63b1e8a1280373c7c046671638f160118b7",
          "sha256": "59578031c4aa94422795a97f370b41889905c485550796b4a615078aff2a567f",
          "sha1": "ca36e851be8aa791ab80409a0bd08b92ae22065e",
          "md5": "7642082e1e154344c9ee8588a654bca3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_release-1.0.aar",
          "url": "device_info_release-1.0.aar",
          "size": 7939,
          "sha512": "84801cf178e1cbdff4c8d043cab3bf1c4e111c1ee390ca7127722ad7145ba881851b32614f62778095c0dec04fcab63b1e8a1280373c7c046671638f160118b7",
          "sha256": "59578031c4aa94422795a97f370b41889905c485550796b4a615078aff2a567f",
          "sha1": "ca36e851be8aa791ab80409a0bd08b92ae22065e",
          "md5": "7642082e1e154344c9ee8588a654bca3"
        }
      ]
    }
  ]
}
