{
  "formatVersion": "1.1",
  "component": {
    "group": "appmire.be.flutterjailbreakdetection",
    "module": "flutter_jailbreak_detection_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_jailbreak_detection_debug-1.0.aar",
          "url": "flutter_jailbreak_detection_debug-1.0.aar",
          "size": 5233,
          "sha512": "c68abba0d4dce12ea80ed87e5c63006276aeb620170ca64ccde7cc10ecab2b3605cda53eac8b6d748bf3a5c2b69d2317b6059c4b93048dac09c8206a085913a0",
          "sha256": "8ec3a7e80aeff4da23209150ab4cfacacfc828406acaf7b492693113443c9cc1",
          "sha1": "124a6a6c42742b4a21a0c1613d90da681a2f9ba0",
          "md5": "dd96d16734b0768d3b26da96078e0fe1"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.github.scottyab",
          "module": "rootbeer",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_jailbreak_detection_debug-1.0.aar",
          "url": "flutter_jailbreak_detection_debug-1.0.aar",
          "size": 5233,
          "sha512": "c68abba0d4dce12ea80ed87e5c63006276aeb620170ca64ccde7cc10ecab2b3605cda53eac8b6d748bf3a5c2b69d2317b6059c4b93048dac09c8206a085913a0",
          "sha256": "8ec3a7e80aeff4da23209150ab4cfacacfc828406acaf7b492693113443c9cc1",
          "sha1": "124a6a6c42742b4a21a0c1613d90da681a2f9ba0",
          "md5": "dd96d16734b0768d3b26da96078e0fe1"
        }
      ]
    }
  ]
}
