{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-1.0.aar",
          "url": "device_info_plus_release-1.0.aar",
          "size": 9530,
          "sha512": "1cbebd4165549d8c74147a772f9dad52a98a2ca842423983c176e87bc72f1a08715c38871dc7078bf2025adbadbe15bb4c53ad1b1d3e044e1bf2c168c29c8043",
          "sha256": "326a961de5f9731d933f3d3e3101425da42b4d10fc948ace5079bb6c0c718010",
          "sha1": "7d06235e1c1acbb4c8d81186b6607f16e3c6f9d8",
          "md5": "2de64242e69ccb6c530f102789b88f7e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-1.0.aar",
          "url": "device_info_plus_release-1.0.aar",
          "size": 9530,
          "sha512": "1cbebd4165549d8c74147a772f9dad52a98a2ca842423983c176e87bc72f1a08715c38871dc7078bf2025adbadbe15bb4c53ad1b1d3e044e1bf2c168c29c8043",
          "sha256": "326a961de5f9731d933f3d3e3101425da42b4d10fc948ace5079bb6c0c718010",
          "sha1": "7d06235e1c1acbb4c8d81186b6607f16e3c6f9d8",
          "md5": "2de64242e69ccb6c530f102789b88f7e"
        }
      ]
    }
  ]
}
