{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 146184,
          "sha512": "48ce3f6a7d50555b415bac52da2c3d12e67e1aaf8fd6f527a6da176bb93fce3be82b3c35681afc803902c35ba8f1bfbdc089c35ce25d79d294c1f3887c5584ac",
          "sha256": "e822e761d7918d85df6194ea64a0b3cc6d96371e40e1c8264151e2d1abd6dc91",
          "sha1": "203bade766e5bae850deb406f49f7497581b2de4",
          "md5": "b0ffcc3151ab979e04bac7f9e6b99b92"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 146184,
          "sha512": "48ce3f6a7d50555b415bac52da2c3d12e67e1aaf8fd6f527a6da176bb93fce3be82b3c35681afc803902c35ba8f1bfbdc089c35ce25d79d294c1f3887c5584ac",
          "sha256": "e822e761d7918d85df6194ea64a0b3cc6d96371e40e1c8264151e2d1abd6dc91",
          "sha1": "203bade766e5bae850deb406f49f7497581b2de4",
          "md5": "b0ffcc3151ab979e04bac7f9e6b99b92"
        }
      ]
    }
  ]
}
