{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-1.0.aar",
          "url": "share_plus_release-1.0.aar",
          "size": 22330,
          "sha512": "ee3ea42772379ba03a4217b11c785329268593be0ed87a7874343878185cde1d171f7026041174fc2721a70052a8fe6434f541ff30c5df8273ab2a473f91b8f8",
          "sha256": "1054eac16c9f70526c6aa797faf77d154a6d5d7e1e4762a786461ffa8599e7ef",
          "sha1": "1fca5d12209a54242521e614897f8316f1d496ea",
          "md5": "76aba0cd9cdfe8219feba89cf35e5f8f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-1.0.aar",
          "url": "share_plus_release-1.0.aar",
          "size": 22330,
          "sha512": "ee3ea42772379ba03a4217b11c785329268593be0ed87a7874343878185cde1d171f7026041174fc2721a70052a8fe6434f541ff30c5df8273ab2a473f91b8f8",
          "sha256": "1054eac16c9f70526c6aa797faf77d154a6d5d7e1e4762a786461ffa8599e7ef",
          "sha1": "1fca5d12209a54242521e614897f8316f1d496ea",
          "md5": "76aba0cd9cdfe8219feba89cf35e5f8f"
        }
      ]
    }
  ]
}
