{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-1.0.aar",
          "url": "device_info_plus_debug-1.0.aar",
          "size": 9840,
          "sha512": "fd789b05627a03d700e012d90e00a9dfd2b1d5d49c70ccbf1fa3399c74ce35be44df8cac0a5643661ef8218a89d4437f14a3c1c11996032b0167fc256cc6d093",
          "sha256": "04cddc4af16c49fb37164be4a531c6c9037a8c8fb465307a0aa0f1ce84f03b30",
          "sha1": "805cae0e9b27b8b3d9da80156216854d16d52004",
          "md5": "a4963ad1cf5236cef0578471fa233695"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-1.0.aar",
          "url": "device_info_plus_debug-1.0.aar",
          "size": 9840,
          "sha512": "fd789b05627a03d700e012d90e00a9dfd2b1d5d49c70ccbf1fa3399c74ce35be44df8cac0a5643661ef8218a89d4437f14a3c1c11996032b0167fc256cc6d093",
          "sha256": "04cddc4af16c49fb37164be4a531c6c9037a8c8fb465307a0aa0f1ce84f03b30",
          "sha1": "805cae0e9b27b8b3d9da80156216854d16d52004",
          "md5": "a4963ad1cf5236cef0578471fa233695"
        }
      ]
    }
  ]
}
