{
  "formatVersion": "1.1",
  "component": {
    "group": "appmire.be.flutterjailbreakdetection",
    "module": "flutter_jailbreak_detection_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_jailbreak_detection_release-1.0.aar",
          "url": "flutter_jailbreak_detection_release-1.0.aar",
          "size": 5064,
          "sha512": "bae31f420605f501bcf819ca2b5c94c9e44f51f75e16d74d9513cb3e575033972731f18c67a8667b287acf6af138599ac3e9e07a9599bbf4ce72d4c77b0245f8",
          "sha256": "c8b5d0ae4580476df78033ae3771ae4d86a9ef6b5421a9786f32b867547f9474",
          "sha1": "05df26af06219e1d71d2c27b30f705c15a9cc5d4",
          "md5": "eacd53d11742cb09f92adc3b220697b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.github.scottyab",
          "module": "rootbeer",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_jailbreak_detection_release-1.0.aar",
          "url": "flutter_jailbreak_detection_release-1.0.aar",
          "size": 5064,
          "sha512": "bae31f420605f501bcf819ca2b5c94c9e44f51f75e16d74d9513cb3e575033972731f18c67a8667b287acf6af138599ac3e9e07a9599bbf4ce72d4c77b0245f8",
          "sha256": "c8b5d0ae4580476df78033ae3771ae4d86a9ef6b5421a9786f32b867547f9474",
          "sha1": "05df26af06219e1d71d2c27b30f705c15a9cc5d4",
          "md5": "eacd53d11742cb09f92adc3b220697b8"
        }
      ]
    }
  ]
}
