{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.packageinfo",
    "module": "package_info_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_debug-1.0.aar",
          "url": "package_info_plus_debug-1.0.aar",
          "size": 8232,
          "sha512": "9904ff15b8f96123dc966a8afd208778f67802cb56171bc0f109576e4a36b7b37973edec5b03063130b48575337f4b160693eaf094bb228af5e7adc9abc08d62",
          "sha256": "a6584586e2c62a74a34c8599aa9b7c21c7acbacab8f228a6e9ee388ad0dbffe7",
          "sha1": "85e7e42d15c79a564e42b0e69de3c9294088e254",
          "md5": "ef2364585f51a014250ba3f7e3a22e11"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_debug-1.0.aar",
          "url": "package_info_plus_debug-1.0.aar",
          "size": 8232,
          "sha512": "9904ff15b8f96123dc966a8afd208778f67802cb56171bc0f109576e4a36b7b37973edec5b03063130b48575337f4b160693eaf094bb228af5e7adc9abc08d62",
          "sha256": "a6584586e2c62a74a34c8599aa9b7c21c7acbacab8f228a6e9ee388ad0dbffe7",
          "sha1": "85e7e42d15c79a564e42b0e69de3c9294088e254",
          "md5": "ef2364585f51a014250ba3f7e3a22e11"
        }
      ]
    }
  ]
}
