{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jrai.flutter_keyboard_visibility",
    "module": "flutter_keyboard_visibility_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_keyboard_visibility_debug-1.0.aar",
          "url": "flutter_keyboard_visibility_debug-1.0.aar",
          "size": 5124,
          "sha512": "2a7df74e1eda3d1f9b9ad6291f606e62e2829ff07ee0b49715a8b511dbf54630ce70b508967de0349d1fb7489e3e9ddadb11d2a65b318908b0e5781c85ef81ff",
          "sha256": "d85d933371d13f4d0a5758418456986d07fb4a3c85a12aaaf4503748a87d5330",
          "sha1": "2f133d97215310a72686522171de6a1e20027e74",
          "md5": "71db606e03028ef7053f948aa16e773d"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_keyboard_visibility_debug-1.0.aar",
          "url": "flutter_keyboard_visibility_debug-1.0.aar",
          "size": 5124,
          "sha512": "2a7df74e1eda3d1f9b9ad6291f606e62e2829ff07ee0b49715a8b511dbf54630ce70b508967de0349d1fb7489e3e9ddadb11d2a65b318908b0e5781c85ef81ff",
          "sha256": "d85d933371d13f4d0a5758418456986d07fb4a3c85a12aaaf4503748a87d5330",
          "sha1": "2f133d97215310a72686522171de6a1e20027e74",
          "md5": "71db606e03028ef7053f948aa16e773d"
        }
      ]
    }
  ]
}
