{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.deviceinfo",
    "module": "device_info_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_debug-1.0.aar",
          "url": "device_info_debug-1.0.aar",
          "size": 8228,
          "sha512": "cad2b44c651f9ba5f74a921f3261e9a5dce3a3b5ae33599927f284a618ba784e9ab66db64dd5708b418193696de474f8b6373ef096a8fa1b105bb2c8c2092bf9",
          "sha256": "a134191d7ca9a263e7d5b408df70438aa5fcfe4ca10e7585d65ae992870af8fe",
          "sha1": "2963977596530bb9eddfa59bf9bbc88e675af7bc",
          "md5": "1ba32e024ebdef8b5e10117d5335b167"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_debug-1.0.aar",
          "url": "device_info_debug-1.0.aar",
          "size": 8228,
          "sha512": "cad2b44c651f9ba5f74a921f3261e9a5dce3a3b5ae33599927f284a618ba784e9ab66db64dd5708b418193696de474f8b6373ef096a8fa1b105bb2c8c2092bf9",
          "sha256": "a134191d7ca9a263e7d5b408df70438aa5fcfe4ca10e7585d65ae992870af8fe",
          "sha1": "2963977596530bb9eddfa59bf9bbc88e675af7bc",
          "md5": "1ba32e024ebdef8b5e10117d5335b167"
        }
      ]
    }
  ]
}
