{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.localauth",
    "module": "local_auth_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_debug-1.0.aar",
          "url": "local_auth_android_debug-1.0.aar",
          "size": 41900,
          "sha512": "a97e587d3b4987fcbd663ba27ba0036c61924c3d41a23d611997000f7ef4eab703d5ba87a0f78368e0e34894febee7ef6cd440adbb53ab1550d04efc289d9fe8",
          "sha256": "cca1537f628cc3df2a1b05ad719788384a2b1b600c35eba15194059024a8e26d",
          "sha1": "6821a25bf6ee9ae02d007ab06cd5f7e4f7b83092",
          "md5": "22137d73c440cf9d6efee69a0e3ecbc4"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.10"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_debug-1.0.aar",
          "url": "local_auth_android_debug-1.0.aar",
          "size": 41900,
          "sha512": "a97e587d3b4987fcbd663ba27ba0036c61924c3d41a23d611997000f7ef4eab703d5ba87a0f78368e0e34894febee7ef6cd440adbb53ab1550d04efc289d9fe8",
          "sha256": "cca1537f628cc3df2a1b05ad719788384a2b1b600c35eba15194059024a8e26d",
          "sha1": "6821a25bf6ee9ae02d007ab06cd5f7e4f7b83092",
          "md5": "22137d73c440cf9d6efee69a0e3ecbc4"
        }
      ]
    }
  ]
}
