{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jrai.flutter_keyboard_visibility",
    "module": "flutter_keyboard_visibility_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_keyboard_visibility_release-1.0.aar",
          "url": "flutter_keyboard_visibility_release-1.0.aar",
          "size": 4919,
          "sha512": "011cf9f6dd840852fbc641c49de05cab2edfe66f0ac55f78bd5cc11001092e6ba96e321450f41537c1b0c57f45d9f416b4fea08b6bac027d1500eec9582a51ab",
          "sha256": "f32aaf39c3ce5a9a71b971761343b6b5ac2c3344c0f744acafae938d5abee86b",
          "sha1": "4e9d5293a5923619b347efb51350f39bd5fa7403",
          "md5": "efbe69c9ffaa10e4feadade26d0ff4c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_keyboard_visibility_release-1.0.aar",
          "url": "flutter_keyboard_visibility_release-1.0.aar",
          "size": 4919,
          "sha512": "011cf9f6dd840852fbc641c49de05cab2edfe66f0ac55f78bd5cc11001092e6ba96e321450f41537c1b0c57f45d9f416b4fea08b6bac027d1500eec9582a51ab",
          "sha256": "f32aaf39c3ce5a9a71b971761343b6b5ac2c3344c0f744acafae938d5abee86b",
          "sha1": "4e9d5293a5923619b347efb51350f39bd5fa7403",
          "md5": "efbe69c9ffaa10e4feadade26d0ff4c7"
        }
      ]
    }
  ]
}
