{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-1.0.aar",
          "url": "permission_handler_android_release-1.0.aar",
          "size": 28854,
          "sha512": "2a7586416b7dad1a8bb23577ac6e058e3644a38dbe6bd694673a48c72d70c0366060c73386c0e864eed84339b9b2fadb0f12fa1946b6854b90e7dc093439a4fc",
          "sha256": "5c7e003e884c643942ec20289470aca48ce18cd8fbb003985a870f832bc0ae88",
          "sha1": "aff4c2f37d5d19cc35e0099f80170909a3252ae0",
          "md5": "8245911780d48fb8d6172cb16ab8e6b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-1.0.aar",
          "url": "permission_handler_android_release-1.0.aar",
          "size": 28854,
          "sha512": "2a7586416b7dad1a8bb23577ac6e058e3644a38dbe6bd694673a48c72d70c0366060c73386c0e864eed84339b9b2fadb0f12fa1946b6854b90e7dc093439a4fc",
          "sha256": "5c7e003e884c643942ec20289470aca48ce18cd8fbb003985a870f832bc0ae88",
          "sha1": "aff4c2f37d5d19cc35e0099f80170909a3252ae0",
          "md5": "8245911780d48fb8d6172cb16ab8e6b8"
        }
      ]
    }
  ]
}
