{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0.aar",
          "url": "flutter_secure_storage_release-1.0.aar",
          "size": 26673,
          "sha512": "c812e7ef8bef3d681c1722f2e76a468e37012dfc4d48265e8adc5ee510e9b4e9bd226844d96ecd4257384e71866f1f33a1db46b43cd7f67ff118180d9e1929dc",
          "sha256": "014bf2b48c042bf5c6ca2b22e50848091979724347717ce9d157b074734d5127",
          "sha1": "dbd1f4cd2a2f542c1f70cf71f8ab20971c8b83a0",
          "md5": "7feb8683bf404a64db3fe1ca2bcd0c0d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0.aar",
          "url": "flutter_secure_storage_release-1.0.aar",
          "size": 26673,
          "sha512": "c812e7ef8bef3d681c1722f2e76a468e37012dfc4d48265e8adc5ee510e9b4e9bd226844d96ecd4257384e71866f1f33a1db46b43cd7f67ff118180d9e1929dc",
          "sha256": "014bf2b48c042bf5c6ca2b22e50848091979724347717ce9d157b074734d5127",
          "sha1": "dbd1f4cd2a2f542c1f70cf71f8ab20971c8b83a0",
          "md5": "7feb8683bf404a64db3fe1ca2bcd0c0d"
        }
      ]
    }
  ]
}
