{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.0.aar",
          "url": "url_launcher_android_debug-1.0.aar",
          "size": 24498,
          "sha512": "b12c826a7795e1c1336343c0e3fa50bb536fec5528471254e513f8a5ea477a4dcd2b9115c4b08009f1d655a1082d6c868845a02d49e5109249bbdd67d211f3ea",
          "sha256": "272aef2b093a4a72944901623b3e2fce8600a18da99007c5d3aab5ff73ae5451",
          "sha1": "dbe3f12b52673cbede74b8c9b4c81411b588608e",
          "md5": "1e722f54e616528a921ec8127249562e"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a5c24f538d05aaf66f7972fb23959d8cafb9f95a"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.0.aar",
          "url": "url_launcher_android_debug-1.0.aar",
          "size": 24498,
          "sha512": "b12c826a7795e1c1336343c0e3fa50bb536fec5528471254e513f8a5ea477a4dcd2b9115c4b08009f1d655a1082d6c868845a02d49e5109249bbdd67d211f3ea",
          "sha256": "272aef2b093a4a72944901623b3e2fce8600a18da99007c5d3aab5ff73ae5451",
          "sha1": "dbe3f12b52673cbede74b8c9b4c81411b588608e",
          "md5": "1e722f54e616528a921ec8127249562e"
        }
      ]
    }
  ]
}
